
/*tasksInDays = {

 (day_1): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Pyykkien viikkaus, pesu ja ripustus", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Pöytä puhtaaksi", done: false }
],
(day_2): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Kissanhiekka", done: false },
    { name: "Roskat ulos", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
],
(day_3): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Pyykkien viikkaus, pesu ja ripustus", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_4): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Lattioiden siivous + imurointi", done: false },
    { name: "Vessan pesu", done: false },
    { name: "Makkarin siivous", done: false },
    { name: "Kissanhiekka", done: false },
    { name: "Roskat ulos", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_5): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Pyykkien viikkaus, pesu ja ripustus", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_6): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Kissanhiekka", done: false },
    { name: "Roskat ulos", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_7): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Pyykkien viikkaus, pesu ja ripustus", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Pöytä puhtaaksi", done: false },
    { name: "Tilaa ruokaa viikoksi", done: false }
    ],
(day_8): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Ota ruuat vastaan", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Ruuanlaitto", done: false },
    { name: "Kissanhiekka", done: false },
    { name: "Roskat ulos", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_9): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Ruuanlaitto", done: false },
    { name: "Pyykkien viikkaus, pesu ja ripustus", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_10): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Ruuanlaitto", done: false },
    { name: "Kissanhiekka", done: false },
    { name: "Roskat ulos", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_11): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Ruuanlaitto", done: false },
    { name: "Lattioiden siivous + imurointi", done: false },
    { name: "Vessan pesu", done: false },
    { name: "Makkarin siivous", done: false },
    { name: "Lastenhuoneen siivous", done: false },
    { name: "Pyykkien viikkaus, pesu ja ripustus", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_12): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Ruuanlaitto", done: false },
    { name: "Kissanhiekka", done: false },
    { name: "Roskat ulos", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_13): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Ruuanlaitto", done: false },
    { name: "Pyykkien viikkaus, pesu ja ripustus", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_14): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Ruuanlaitto", done: false },
    { name: "Kissanhiekka", done: false },
    { name: "Roskat ulos", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_15): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Pyykkien viikkaus, pesu ja ripustus", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_16): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Kissanhiekka", done: false },
    { name: "Roskat ulos", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_17): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Pyykkien viikkaus, pesu ja ripustus", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_18): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Lattioiden siivous + imurointi", done: false },
    { name: "Lattioiden pesu", done: false },
    { name: "Vessan pesu", done: false },
    { name: "Makkarin siivous", done: false },
    { name: "Kissanhiekka", done: false },
    { name: "Roskat ulos", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_19): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Pyykkien viikkaus, pesu ja ripustus", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_20): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Kissanhiekka", done: false },
    { name: "Roskat ulos", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_21): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Pyykkien viikkaus, pesu ja ripustus", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Pöytä puhtaaksi", done: false },
    { name: "Tilaa ruokaa viikoksi", done: false }
    ],
(day_22): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Ota ruuat vastaan", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Ruuanlaitto", done: false },
    { name: "Kissanhiekka", done: false },
    { name: "Roskat ulos", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_23): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Ruuanlaitto", done: false },
    { name: "Pyykkien viikkaus, pesu ja ripustus", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_24): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Ruuanlaitto", done: false },
    { name: "Kissanhiekka", done: false },
    { name: "Roskat ulos", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_25): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Ruuanlaitto", done: false },
    { name: "Lattioiden siivous + imurointi", done: false },
    { name: "Vessan pesu", done: false },
    { name: "Makkarin siivous", done: false },
    { name: "Lastenhuoneen siivous", done: false },
    { name: "Lakanoiden vaihto", done: false },
    { name: "Pyykkien viikkaus, pesu ja ripustus", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_26): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Ruuanlaitto", done: false },
    { name: "Kissanhiekka", done: false },
    { name: "Roskat ulos", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_27): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Ruuanlaitto", done: false },
    { name: "Pyykkien viikkaus, pesu ja ripustus", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
(day_28): [
    { name: "Koiran aamulenkki + ruoka", done: false },
    { name: "Kissan aamupala", done: false },
    { name: "Tiskikone tyhjäksi", done: false },
    { name: "Koiran päivälenkki", done: false },
    { name: "Kissan + koiran iltapala", done: false },
    { name: "Ruuanlaitto", done: false },
    { name: "Kissanhiekka", done: false },
    { name: "Roskat ulos", done: false },
    { name: "Koiran iltalenkki", done: false },
    { name: "Tiskikone päälle", done: false },
    { name: "Pöytä puhtaaksi", done: false }
    ],
}

*/