import { Task } from './task';


export const tasksInDays = {

 day_1: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Pyykkien viikkaus, pesu ja ripustus", false),
    new Task("Iltalenkki", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
],
day_2: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Kissanhiekka", false),
    new Task("Roskat ulos", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
],
day_3: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Pyykkien viikkaus, pesu ja ripustus", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Iltalenkki", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_4: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Lattioiden siivous + imurointi", false),
    new Task("Vessan pesu", false),
    new Task("Makkarin siivous", false),
    new Task("Kissanhiekka", false),
    new Task("Roskat ulos", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_5: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Pyykkien viikkaus, pesu ja ripustus", false),
    new Task("Iltalenkki", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_6: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Kissanhiekka", false),
    new Task("Roskat ulos", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_7: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Pyykkien viikkaus, pesu ja ripustus", false),
    new Task("Iltalenkki", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Tila+ lemmikkien ruokaa viikoksi", false),
    new Task("Iltacheckaus", false)
    ],
day_8: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Päivälenkki", false),
    new Task("Ota ruuat vastaan", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Ruuanlaitto", false),
    new Task("Kissanhiekka", false),
    new Task("Roskat ulos", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_9: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Ruuanlaitto", false),
    new Task("Pyykkien viikkaus, pesu ja ripustus", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_10: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Ruuanlaitto", false),
    new Task("Kissanhiekka", false),
    new Task("Roskat ulos", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_11: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Ruuanlaitto", false),
    new Task("Pyykkien viikkaus, pesu ja ripustus", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_12: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Ruuanlaitto", false),
    new Task("Lattioiden siivous + imurointi", false),
    new Task("Vessan pesu", false),
    new Task("Makkarin siivous", false),
    new Task("Lastenhuoneen siivous", false),
    new Task("Kissanhiekka", false),
    new Task("Roskat ulos", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_13: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Ruuanlaitto", false),
    new Task("Pyykkien viikkaus, pesu ja ripustus", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_14: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Ruuanlaitto", false),
    new Task("Kissanhiekka", false),
    new Task("Roskat ulos", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_15: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Pyykkien viikkaus, pesu ja ripustus", false),
    new Task("Iltalenkki", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_16: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Kissanhiekka", false),
    new Task("Roskat ulos", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_17: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Pyykkien viikkaus, pesu ja ripustus", false),
    new Task("Iltalenkki", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_18: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Lattioiden siivous + imurointi", false),
    new Task("Lattioiden pesu", false),
    new Task("Vessan pesu", false),
    new Task("Makkarin siivous", false),
    new Task("Kissanhiekka", false),
    new Task("Roskat ulos", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_19: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Pyykkien viikkaus, pesu ja ripustus", false),
    new Task("Iltalenkki", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_20: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Kissanhiekka", false),
    new Task("Roskat ulos", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_21: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Pyykkien viikkaus, pesu ja ripustus", false),
    new Task("Iltalenkki", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Tila+ lemmikkien ruokaa viikoksi", false),
    new Task("Iltacheckaus", false)
    ],
day_22: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Päivälenkki", false),
    new Task("Ota ruuat vastaan", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Ruuanlaitto", false),
    new Task("Kissanhiekka", false),
    new Task("Roskat ulos", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_23: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Ruuanlaitto", false),
    new Task("Pyykkien viikkaus, pesu ja ripustus", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_24: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Ruuanlaitto", false),
    new Task("Kissanhiekka", false),
    new Task("Roskat ulos", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_25: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Ruuanlaitto", false),
    new Task("Pyykkien viikkaus, pesu ja ripustus", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_26: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Ruuanlaitto", false),
    new Task("Lattioiden siivous + imurointi", false),
    new Task("Vessan pesu", false),
    new Task("Makkarin siivous", false),
    new Task("Lastenhuoneen siivous", false),
    new Task("Lakanoiden vaihto", false),
    new Task("Kissanhiekka", false),
    new Task("Roskat ulos", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_27: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Ruuanlaitto", false),
    new Task("Pyykkien viikkaus, pesu ja ripustus", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
day_28: [
    new Task("Aamulenkki + lemmikkien ruoka", false),
    new Task("Tiskikone tyhjäksi", false),
    new Task("Päivälenkki", false),
    new Task("Kissan + koiran iltapala", false),
    new Task("Ruuanlaitto", false),
    new Task("Kissanhiekka", false),
    new Task("Roskat ulos", false),
    new Task("Iltalenkki", false),
    new Task("Tiskikone päälle", false),
    new Task("Pöytä puhtaaksi", false),
    new Task("Iltacheckaus", false)
    ],
}

